project 'KxMemoObjc.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KxMemoObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KxMemoObjc
  pod 'QRCodeReaderViewController', '~> 4.0.2'
end
